name: Backend CI/CD

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm test
        env:
          NODE_ENV: test
          PORT: 5500
          JWT_SECRET: testsecret
          JWT_EXPIRATION: 1d
          DB_URI: mongodb://localhost:27017/testdb

  deploy:
    name: Deploy to Render
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deploy Hook
        run: |
          if [ -z "${{ secrets.RENDER_DEPLOY_HOOK }}" ]; then
            echo "Error: RENDER_DEPLOY_HOOK secret is not set."
            exit 1
          fi
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
